name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Compile TypeScript files
      run: |
        npx tsc || (echo "TypeScript compilation failed" && exit 1)
    
    - name: Run Test1
      run: |
        node dist/Test1.js
